# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-15 12:03
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('details_id', models.IntegerField(primary_key=True, serialize=False)),
                ('details_url', models.CharField(max_length=100, null=True)),
                ('details_title', models.CharField(max_length=100, null=True)),
                ('details_zz', models.CharField(max_length=100, null=True)),
                ('details_js', models.CharField(max_length=500, null=True)),
                ('details_hot', models.IntegerField(null=True)),
                ('image_url', models.CharField(max_length=100, null=True)),
                ('image_figer', models.CharField(max_length=100, null=True)),
                ('a_content', DjangoUeditor.models.UEditorField(blank=True, default='0', verbose_name='文章内容')),
            ],
            options={
                'verbose_name': '详情',
                'db_table': 'details',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('home_id', models.IntegerField(primary_key=True, serialize=False)),
                ('home_title', models.CharField(max_length=100, null=True)),
                ('home_url', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': '导航',
                'db_table': 'home',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('phone', models.CharField(default='110', max_length=11)),
                ('desc', models.CharField(max_length=255, null=True)),
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('icon', models.ImageField(default='apps/static/img/default.png', upload_to='upload/img/%Y%m%d', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='Zhangjie',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('read_title', models.CharField(max_length=100, null=True)),
                ('read_url', models.CharField(max_length=100, null=True)),
                ('read_zj', models.CharField(max_length=100, null=True)),
                ('details_id', models.ForeignKey(db_column='details_id', on_delete=django.db.models.deletion.DO_NOTHING, to='art_app.Details')),
            ],
            options={
                'verbose_name': '章节',
                'db_table': 'zhangjie',
            },
        ),
        migrations.AddField(
            model_name='details',
            name='home_id',
            field=models.ForeignKey(db_column='home_id', on_delete=django.db.models.deletion.DO_NOTHING, to='art_app.Home'),
        ),
    ]
